# Generated by Django 5.0.7 on 2024-08-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='date_specified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
